// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCookie() {
  return window['go']['archery']['Archery']['GetCookie']();
}

export function SetCookie(arg1, arg2) {
  return window['go']['archery']['Archery']['SetCookie'](arg1, arg2);
}
