// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCookie():Promise<{[key: string]: string}>;

export function SetCookie(arg1:string,arg2:string):Promise<void>;
